pull_request_rules:
- actions:
    queue:
      method: fast-forward
      name: default
  conditions:
  - base=20230608152204/test_queue_fast_forward/main
  - label=queue
  name: merge fast-forward
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
