pull_request_rules:
- actions:
    queue:
      merge_method: fast-forward
      name: default
  conditions:
  - base=20230726160351/test_queue_fast_forward_with_retries/main
  - label=queue
  name: merge fast-forward
queue_rules:
- merge_conditions:
  - label=merge
  name: default
