pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230906143834/test_queue_freeze_checks_end_emitted_anyway/main
  - label=queue
  name: queue_to_default
queue_rules:
- merge_conditions:
  - check-success=waiting
  name: default
