pull_request_rules:
- actions:
    comment:
      message: Hello!
  conditions:
  - base=20230830084805/test_eventlogsX/main
  - label=auto-merge
  name: hello
- actions:
    assign:
      users:
      - mergify-test1
    label:
      add:
      - need-review
      remove:
      - auto-merge
    merge: {}
  conditions:
  - base=20230830084805/test_eventlogsX/main
  name: mergeit
