pull_request_rules:
- actions:
    comment:
      message: head repository full name is {{ head_repo_full_name }}
  conditions:
  - head-repo-full-name=https://github.com/mergifyio-testing/functional-testing-repo-lecrepont01/tree/20231023121929/test_head_repo_full_name/integration/pr1
  name: no-draft
