pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - inputs:
            some_boolean: true
          workflow: pep8_workflow
        - inputs:
            some_number: '11'
            some_string: Hello
          workflow: ci_workflow
  conditions:
  - label=dispatch
  name: Dispatch GHA
