pull_request_rules:
- actions:
    comment:
      message: head-repo-full-name={{ head_repo_full_name }}
  conditions:
  - head-repo-full-name=https://github.com/mergifyio-testing/functional-testing-repo-lecrepont01/tree/20231023122147/test_head_repo_full_name/integration/pr1
  name: no-draft
