pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230612123539/test_handle_merge_error/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
