pull_request_rules:
- actions:
    comment:
      message: head-repo-full-name={{ head_repo_full_name }}
  conditions:
  - head-repo-full-name=mergify-test2/functional-testing-repo-lecrepont01
  name: no-draft
