pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230811093137/test_queue_ci_timeout_inplace/main
  - check-success=continuous-integration/fake-ci
  name: queue
queue_rules:
- checks_timeout: 10m
  conditions:
  - check-success=continuous-integration/fake-ci
  name: default
