pull_request_rules:
- actions:
    request_reviews:
      users:
      - FakeUserBlablablaRandom
  conditions:
  - base=20230427155915/test_request_reviews_unknown_reviewer/main
  name: request_reviews
