pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - workflow: multiple_workflows_success
        - inputs:
            some_string: 666
          workflow: multiple_workflows_error
  conditions:
  - label=dispatch
  name: Dispatch GHA
