pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - ref: branch-does-not-exist
          workflow: fork_workflow.yaml
  conditions:
  - label=dispatch
  name: Dispatch GHA
