pull_request_rules:
- actions:
    github_actions:
      workflow:
        dispatch:
        - inputs:
            some_number: 42
          workflow: inputs_required
  conditions:
  - label=dispatch
  name: Dispatch GHA
