pull_request_rules:
- actions:
    assign:
      users:
      - mergify-test1
    label:
      add:
      - toto
  conditions:
  - base=20230725123341/test_eventlogs_db/main
  name: Assign and label
- actions:
    queue: {}
  conditions:
  - label=toto
  name: Queue to default
queue_rules:
- checks_timeout: 10 m
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  - status-success=continuous-integration/fake-ci_2
  name: default
