pull_request_rules:
- actions:
    queue: {}
  conditions:
  - label=queue
  name: Queue
queue_rules:
- name: hotfix
  routing_conditions:
  - label=will-not-be-set
- name: pending-check-success
  routing_conditions:
  - check-success=check
