pull_request_rules:
- actions:
    queue: {}
  conditions:
  - label=queue
  name: Queue
queue_rules:
- name: pending-check-success
  routing_conditions:
  - check-success=pending-check
- name: default
