jobs:
  test-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      run: echo hello world
name: workflow_on_fork
'on':
  pull_request:
    branches: 20231027141326/test_gha_passed_ref/main
  workflow_dispatch:
    inputs: {}
