jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Test dispatched workflow inputs
      run: echo some_boolean=${{ inputs.some_boolean }}
    timeout-minutes: 5
name: pep8
'on':
  workflow_dispatch:
    inputs:
      some_boolean:
        required: true
        type: boolean
